#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 7.1
#  in conjunction with Tcl version 8.6
#    Jan 16, 2022 06:16:13 PM NST  platform: Linux

import sys
import tkinter as tk
from tkinter.messagebox import *
import tkinter.ttk as ttk
from tkinter.constants import *

import ptrail_gui


def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol('WM_DELETE_WINDOW', root.destroy)
    # Creates a toplevel widget.

    global _top1, _w1
    _top1 = root
    _w1 = ptrail_gui.MainCanvas(_top1)

    root.config(menu=add_menubar())
    root.mainloop()


def add_menubar():
    """
        Create the Menubar for the frame and return it.

        Returns
        -------
            tkinter.Menu
                The Menubar containing the File and the about menu.

    """
    # Create the menubar.
    menubar = tk.Menu(root)

    # Create the File Menu.
    filemenu = tk.Menu(menubar, tearoff=0)
    filemenu.add_command(label="Open", )
    filemenu.add_command(label="Save", )
    filemenu.add_separator()
    filemenu.add_command(label="Exit", command=root.quit)
    menubar.add_cascade(label="File", menu=filemenu)

    # Create the About menu/
    aboutmenu = tk.Menu(menubar, tearoff=0)
    aboutmenu.add_command(label="Version Info", command=show_info)
    menubar.add_cascade(label="About", menu=aboutmenu)

    return menubar


def show_info():
    return showinfo(title="Version info",
                    message="PTRAIL - Trajectory Preprocessing Tool \n"
                            "Version: 0.6.3 Beta \n"
                            "Authors: Yaksh J Haranwala, Salman Haidri")


if __name__ == '__main__':
    support.start_up()
